version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          name: installing packages
          command: npm install
      - run: 
          name: running unit test
          command: yarn test

workflows:
  build_test_workflow:
    jobs:
      - build_and_test